spring:
    config:
        activate:
            on-profile: local

    datasource:
        url: jdbc:mariadb://svc.sel4.cloudtype.app:32389/invu
        username: ${username}
        password: ${password}
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true

cors:
    allowed-origins: http://localhost:3300,https://port-next-invu-client-m78pe23vb8056d68.sel4.cloudtype.app,http://invu-client:3000
