spring:
    config:
        activate:
            on-profile: prod

    datasource:
        url: jdbc:mariadb://mariadb:3306/invu
        username: ${username}
        password: ${password}
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true

cors:
    allowed-origins: https://port-next-invu-client-release-m78pe23vb8056d68.sel4.cloudtype.app, http://invu-client-release:3000, https://invu.devs32.org
