spring:
    application:
        name: InvuApp  # 애플리케이션 이름 설정
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 100MB

    jackson:
        time-zone: Asia/Seoul

    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

server:
    port: 8080  # 서버 포트 설정

cloudflare:
    r2:
        bucket-name: invu
