spring:
    config:
        activate:
            on-profile: dev

    datasource:
        url: jdbc:mariadb://mariadb:3306/invu
        username: ${username}
        password: ${password}
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true

