spring:
    config:
        activate:
            on-profile: dev

    datasource:
        url: jdbc:mariadb://mariadb:3306/invu
        username: ${db_username}
        password: ${db_username}
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true

