spring:
    config:
        activate:
            on-profile: local

    datasource:
        url: ${url}
        username: ${username}
        password: ${password}
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true

server:
    port: 8080  # 서버 포트 설정
